In [38]:
import pandas as pd
import numpy as np
import seaborn as sns
df = pd.read_csv(r"C:\Users\admin\Desktop\Metro_Interstate_Traffic_Volume.csv") #na_values are used to use NaN inplace of ?? in dataset. Nan is standard name for missing value
print("The first 10 rows of the dataframe") 
headers = ["holiday","temp","rain_1h","snow_1h","clouds_all","weather_main","weather_description","date_time","traffic_volume"]
#df.columns shows labels of columns in dataframe
df.columns = headers
df.head(10)

The first 10 rows of the dataframe


holiday    temp  rain_1h  snow_1h  clouds_all weather_main  \
0    None  288.28      0.0      0.0          40       Clouds   
1    None  289.36      0.0      0.0          75       Clouds   
2    None  289.58      0.0      0.0          90       Clouds   
3    None  290.13      0.0      0.0          90       Clouds   
4    None  291.14      0.0      0.0          75       Clouds   
5    None  291.72      0.0      0.0           1        Clear   
6    None  293.17      0.0      0.0           1        Clear   
7    None  293.86      0.0      0.0           1        Clear   
8    None  294.14      0.0      0.0          20       Clouds   
9    None  293.10      0.0      0.0          20       Clouds   

  weather_description            date_time  traffic_volume  
0    scattered clouds  2012-10-02 09:00:00            5545  
1       broken clouds  2012-10-02 10:00:00            4516  
2     overcast clouds  2012-10-02 11:00:00            4767  
3     overcast clouds  2012-10-02 12:00:00            5026  
4       broken clouds  2012-10-02 13:00:00            4918  
5        sky is clear  2012-10-02 14:00:00            5181  
6        sky is clear  2012-10-02 15:00:00            5584  
7        sky is clear  2012-10-02 16:00:00            6015  
8          few clouds  2012-10-02 17:00:00            5791  
9          few clouds  2012-10-02 18:00:00            4770

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48204 entries, 0 to 48203
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   holiday              48204 non-null  object 
 1   temp                 48204 non-null  float64
 2   rain_1h              48204 non-null  float64
 3   snow_1h              48204 non-null  float64
 4   clouds_all           48204 non-null  int64  
 5   weather_main         48204 non-null  object 
 6   weather_description  48204 non-null  object 
 7   date_time            48204 non-null  object 
 8   traffic_volume       48204 non-null  int64  
dtypes: float64(3), int64(2), object(4)
memory usage: 3.3+ MB


In [40]:
df.replace("?",np.nan,inplace =True)
df.head(10)

holiday    temp  rain_1h  snow_1h  clouds_all weather_main  \
0    None  288.28      0.0      0.0          40       Clouds   
1    None  289.36      0.0      0.0          75       Clouds   
2    None  289.58      0.0      0.0          90       Clouds   
3    None  290.13      0.0      0.0          90       Clouds   
4    None  291.14      0.0      0.0          75       Clouds   
5    None  291.72      0.0      0.0           1        Clear   
6    None  293.17      0.0      0.0           1        Clear   
7    None  293.86      0.0      0.0           1        Clear   
8    None  294.14      0.0      0.0          20       Clouds   
9    None  293.10      0.0      0.0          20       Clouds   

  weather_description            date_time  traffic_volume  
0    scattered clouds  2012-10-02 09:00:00            5545  
1       broken clouds  2012-10-02 10:00:00            4516  
2     overcast clouds  2012-10-02 11:00:00            4767  
3     overcast clouds  2012-10-02 12:00:00            5026  
4       broken clouds  2012-10-02 13:00:00            4918  
5        sky is clear  2012-10-02 14:00:00            5181  
6        sky is clear  2012-10-02 15:00:00            5584  
7        sky is clear  2012-10-02 16:00:00            6015  
8          few clouds  2012-10-02 17:00:00            5791  
9          few clouds  2012-10-02 18:00:00            4770

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48204 entries, 0 to 48203
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   holiday              48204 non-null  object 
 1   temp                 48204 non-null  float64
 2   rain_1h              48204 non-null  float64
 3   snow_1h              48204 non-null  float64
 4   clouds_all           48204 non-null  int64  
 5   weather_main         48204 non-null  object 
 6   weather_description  48204 non-null  object 
 7   date_time            48204 non-null  object 
 8   traffic_volume       48204 non-null  int64  
dtypes: float64(3), int64(2), object(4)
memory usage: 3.3+ MB


In [42]:
df.isnull().sum()

holiday                0
temp                   0
rain_1h                0
snow_1h                0
clouds_all             0
weather_main           0
weather_description    0
date_time              0
traffic_volume         0
dtype: int64

In [43]:
df.dtypes

holiday                 object
temp                   float64
rain_1h                float64
snow_1h                float64
clouds_all               int64
weather_main            object
weather_description     object
date_time               object
traffic_volume           int64
dtype: object

In [44]:
df[["temp","rain_1h","snow_1h","clouds_all","traffic_volume"]]=df[["temp","rain_1h","snow_1h","clouds_all","traffic_volume"]].astype("float")
df[["holiday","weather_main","weather_description","date_time"]] = df[["holiday","weather_main","weather_description","date_time"]].astype('str')

In [45]:
df.dtypes

holiday                 object
temp                   float64
rain_1h                float64
snow_1h                float64
clouds_all             float64
weather_main            object
weather_description     object
date_time               object
traffic_volume         float64
dtype: object

In [51]:
df.corr()

temp   rain_1h   snow_1h  clouds_all  traffic_volume
temp            1.000000  0.009069 -0.019755   -0.101976        0.130299
rain_1h         0.009069  1.000000 -0.000090    0.004818        0.004714
snow_1h        -0.019755 -0.000090  1.000000    0.027931        0.000733
clouds_all     -0.101976  0.004818  0.027931    1.000000        0.067054
traffic_volume  0.130299  0.004714  0.000733    0.067054        1.000000

In [52]:
df.corr()["traffic_volume"]

temp              0.130299
rain_1h           0.004714
snow_1h           0.000733
clouds_all        0.067054
traffic_volume    1.000000
Name: traffic_volume, dtype: float64

In [53]:
lst=["temp","rain_1h","snow_1h","clouds_all","traffic_volume"]
lst2=[]
from scipy.stats import pearsonr
for i in lst:
    corr,_ = pearsonr(df["traffic_volume"],df[i])
    print(i,'Pearsons correlation: %.3f' % corr)
    if corr<-0.5 or corr>0.5:
        lst2.append(i)
print(lst2)

temp Pearsons correlation: 0.130
rain_1h Pearsons correlation: 0.005
snow_1h Pearsons correlation: 0.001
clouds_all Pearsons correlation: 0.067
traffic_volume Pearsons correlation: 1.000
['traffic_volume']


In [54]:
##################################
#####################################
#####################

In [55]:
# Importing LabelEncoder from Sklearn
# library from preprocessing Module.
from sklearn.preprocessing import LabelEncoder

# Creating a instance of label Encoder.
le = LabelEncoder()

# Using .fit_transform function to fit label
# encoder and return encoded label
label = le.fit_transform(df['weather_main'])

# printing label
label

array([ 1,  1,  1, ..., 10,  1,  1])

In [57]:
# Importing LabelEncoder from Sklearn
# library from preprocessing Module.
from sklearn.preprocessing import LabelEncoder

# Creating a instance of label Encoder.
le = LabelEncoder()

# Using .fit_transform function to fit label
# encoder and return encoded label
label = le.fit_transform(df['holiday'])

# printing label
label


array([7, 7, 7, ..., 7, 7, 7])

In [58]:
df.drop("holiday", axis=1, inplace=True)
df["holiday"] = label
df

temp  rain_1h  snow_1h  clouds_all     weather_description  \
0      288.28      0.0      0.0        40.0        scattered clouds   
1      289.36      0.0      0.0        75.0           broken clouds   
2      289.58      0.0      0.0        90.0         overcast clouds   
3      290.13      0.0      0.0        90.0         overcast clouds   
4      291.14      0.0      0.0        75.0           broken clouds   
...       ...      ...      ...         ...                     ...   
48199  283.45      0.0      0.0        75.0           broken clouds   
48200  282.76      0.0      0.0        90.0         overcast clouds   
48201  282.73      0.0      0.0        90.0  proximity thunderstorm   
48202  282.09      0.0      0.0        90.0         overcast clouds   
48203  282.12      0.0      0.0        90.0         overcast clouds   

                 date_time  traffic_volume  weather_main  holiday  
0      2012-10-02 09:00:00          5545.0             1        7  
1      2012-10-02 10:00:00          4516.0             1        7  
2      2012-10-02 11:00:00          4767.0             1        7  
3      2012-10-02 12:00:00          5026.0             1        7  
4      2012-10-02 13:00:00          4918.0             1        7  
...                    ...             ...           ...      ...  
48199  2018-09-30 19:00:00          3543.0             1        7  
48200  2018-09-30 20:00:00          2781.0             1        7  
48201  2018-09-30 21:00:00          2159.0            10        7  
48202  2018-09-30 22:00:00          1450.0             1        7  
48203  2018-09-30 23:00:00           954.0             1        7  

[48204 rows x 9 columns]

In [59]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
label = le.fit_transform(df['weather_description'])
label

array([24,  2, 19, ..., 21, 19, 19])

In [60]:
df.drop("weather_description", axis=1, inplace=True)
df["weather_description"] = label
df

temp  rain_1h  snow_1h  clouds_all            date_time  \
0      288.28      0.0      0.0        40.0  2012-10-02 09:00:00   
1      289.36      0.0      0.0        75.0  2012-10-02 10:00:00   
2      289.58      0.0      0.0        90.0  2012-10-02 11:00:00   
3      290.13      0.0      0.0        90.0  2012-10-02 12:00:00   
4      291.14      0.0      0.0        75.0  2012-10-02 13:00:00   
...       ...      ...      ...         ...                  ...   
48199  283.45      0.0      0.0        75.0  2018-09-30 19:00:00   
48200  282.76      0.0      0.0        90.0  2018-09-30 20:00:00   
48201  282.73      0.0      0.0        90.0  2018-09-30 21:00:00   
48202  282.09      0.0      0.0        90.0  2018-09-30 22:00:00   
48203  282.12      0.0      0.0        90.0  2018-09-30 23:00:00   

       traffic_volume  weather_main  holiday  weather_description  
0              5545.0             1        7                   24  
1              4516.0             1        7                    2  
2              4767.0             1        7                   19  
3              5026.0             1        7                   19  
4              4918.0             1        7                    2  
...               ...           ...      ...                  ...  
48199          3543.0             1        7                    2  
48200          2781.0             1        7                   19  
48201          2159.0            10        7                   21  
48202          1450.0             1        7                   19  
48203           954.0             1        7                   19  

[48204 rows x 9 columns]

In [61]:
#important attributes in dataset are:
##'holiday','weather_main','date_time','traffic_volume,'temp','weather_description','clouds_all'

In [62]:
df.corr()["traffic_volume"]

temp                   0.130299
rain_1h                0.004714
snow_1h                0.000733
clouds_all             0.067054
traffic_volume         1.000000
weather_main          -0.040151
holiday                0.018676
weather_description   -0.067507
Name: traffic_volume, dtype: float64

In [63]:
from sklearn.model_selection import train_test_split
#1.divide dataset in test data and train data
#divide x_data and y_data
y_data = df['traffic_volume']
x_data=df.drop('traffic_volume',axis=1)

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=1)
#random_state=1 gives you different results everytime

print("number of test samples :", x_test.shape[0])
print("number of training samples:",x_train.shape[0])

number of test samples : 9641
number of training samples: 38563


In [64]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from sklearn.linear_model import LinearRegression
Z = x_train[['temp', 'clouds_all', 'weather_main', 'holiday','weather_description']]
y=y_train


In [65]:
lm1 = LinearRegression()
df.dtypes
lm1.fit(Z, y)
print(lm1.intercept_)
lm1.coef_

-4369.740730339447


array([ 20.8991151 ,   6.13185513, -74.54296394, 251.24535356,
        -7.00542227])

In [66]:
#predict values
#We can output a prediction
Y_predict_multifit=lm1.predict(Z) # this function is used to predict the price parameter x is array
print("predicted price for 0 to 4 index value is ",Y_predict_multifit[0:5])
print("actual values are",y[0:5])

predicted price for 0 to 4 index value is  [3333.76770116 3056.04249775 3248.94133013 3594.30005155 3298.59066057]
actual values are 6715      812.0
27836    1241.0
43682    1703.0
41005    5829.0
28608    3798.0
Name: traffic_volume, dtype: float64


In [30]:
x1=x_test[['temp', 'clouds_all', 'weather_main', 'holiday','weather_description']]
y_1=y_test

#predit values
#We can output a prediction
Y_predict_multifit1=lm1.predict(x1) # this function is used to predict the price parameter x is array
print("predicted price for 0 to 4 index value is ",Y_predict_multifit1[0:5])
print("actual values are",y_1[0:5])

predicted price for 0 to 4 index value is  [3333.76770116 3056.04249775 3248.94133013 3594.30005155 3298.59066057]
actual values are 6715      812.0
27836    1241.0
43682    1703.0
41005    5829.0
28608    3798.0
Name: traffic_volume, dtype: float64


In [31]:
y_poly_predict=Z
print(y_poly_predict[0:5])
print("actual values:",y[0:5])

         temp  clouds_all  weather_main  holiday  weather_description
16959  300.06        40.0             1        7                   24
6182   297.22         1.0             0        7                   27
42019  276.88        90.0             1        7                   19
14034  283.38        90.0             1        7                   19
5732   273.31        90.0             1        7                   19
actual values: 16959    5445.0
6182     2337.0
42019     756.0
14034     355.0
5732     2299.0
Name: traffic_volume, dtype: float64


In [70]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
#We create the pipeline, by creating a list of tuples including the name of the model or estimator and its corresponding constructor.
Input=[('scale',StandardScaler()), ('polynomial', PolynomialFeatures(3)), ('model',LinearRegression())] # we can also use ridge and lasso regression
#we input the list as an argument to the pipeline constructo
pipe=Pipeline(Input)
pipe


Pipeline(steps=[('scale', StandardScaler()),
                ('polynomial', PolynomialFeatures(degree=3)),
                ('model', LinearRegression())])

In [71]:
#We can normalize the data, perform a transform and fit the model simultaneously.
pipe.fit(Z,y)


Pipeline(steps=[('scale', StandardScaler()),
                ('polynomial', PolynomialFeatures(degree=3)),
                ('model', LinearRegression())])

In [72]:
#We can normalize the data, perform a transform and fit the model simultaneously.
y_poly_predict=pipe.predict(x_test[['temp', 'clouds_all', 'weather_main', 'holiday','weather_description']])


In [73]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
#multi linear regression
print("mutli linear regression model:")
print('R2: ', r2_score(y_1,  Y_predict_multifit1))
print('MSE: ', mean_squared_error(y_1, Y_predict_multifit1))


mutli linear regression model:
R2:  0.029017398462366506
MSE:  3810873.18596569


In [74]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
#polynomial regression
print("mutli linear regression model:")
print('R2: ', r2_score(y_1,  y_poly_predict))
print('MSE: ', mean_squared_error(y_1, y_poly_predict))


mutli linear regression model:
R2:  0.057644081423867344
MSE:  3698520.340169723
